### ISSUE TITLE
Bug in 3.2.0

### ISSUE THREAD

**Issue by ozzy1873** [toshiaki-h/split_view#19] opened 2022-07-22 15:35 UTC
A bug was introduced in 3.2.0. 

`
SplitView(
                viewMode: SplitViewMode.Vertical,
                controller: SplitViewController(weights: [0.35]),
                gripColorActive: AppColors.primaryAccent,
                indicator:
                    const SplitIndicator(viewMode: SplitViewMode.Vertical),
                activeIndicator: const SplitIndicator(
                  viewMode: SplitViewMode.Vertical,
                  isActive: true,
                ),
                children: [
                  _buildMap(),
                  PageView(
                    physics: const NeverScrollableScrollPhysics(),
                    onPageChanged: _onPageChanged,
                    controller: pageController,
                    children: [summary, gps, hr, cad, pwr],
                  ),
                ]);
`

When the page is initially displayed, the SplitView works normally. However, once the PageView is switched to a different page, the SplitView gripColorActive no longer displays and the drag gesture becomes slow and jittery.

Switching back to version 3.1.0 fixes this problem.

**Comment by toshiaki-h** [comment] 2022-07-23 01:02
@ozzy1873 
Thank you for your report.
I had confirmed that the drag gesture slows down when switching to a different page.
However, I could not confirm that gripColorActive was not displayed.
I have retracted 3.2.0 because it is not good for drag gestures to be slow. Thank you.

**Comment by jpnurmi** [comment] 2022-08-07 19:44
@toshiaki-h was this caused by #18? Could you share a runnable example that reproduces the problem?

**Comment by toshiaki-h** [comment] 2022-08-11 07:58
Thanks @jpnurmi.

Here is sample code.
`
import 'package:flutter/material.dart';
import 'package:split_view/split_view.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, this.title}) : super(key: key);

  final String? title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title!),
      ),
      body: SplitView(
        children: [
          SplitView(
            viewMode: SplitViewMode.Horizontal,
            indicator: SplitIndicator(viewMode: SplitViewMode.Horizontal),
            activeIndicator: SplitIndicator(
              viewMode: SplitViewMode.Horizontal,
              isActive: true,
            ),
            gripColorActive: Colors.red,
            children: [
              Container(
                child: Center(child: Text("View1")),
                color: Colors.red,
              ),
              Container(
                child: Center(child: Text("View2")),
                color: Colors.blue,
              ),
              Container(
                child: Center(child: Text("View3")),
                color: Colors.green,
              ),
            ],
            onWeightChanged: (w) => print("Horizon: $w"),
          ),
          Container(
            child: Center(
              child: ElevatedButton(
                child: Text('View4'),
                onPressed: () {
                  Navigator.push(context, MaterialPageRoute(
                    builder: (context) {
                      return DummyPage();
                    },
                  ));
                },
              ),
            ),
            color: Colors.purple,
          ),
          Container(
            child: Center(child: Text("View5")),
            color: Colors.yellow,
          ),
        ],
        viewMode: SplitViewMode.Vertical,
        indicator: SplitIndicator(viewMode: SplitViewMode.Vertical),
        activeIndicator: SplitIndicator(
          viewMode: SplitViewMode.Vertical,
          isActive: true,
        ),
        controller: SplitViewController(limits: [null, WeightLimit(max: 0.5)]),
        onWeightChanged: (w) => print("Vertical $w"),
      ),
    );
  }
}

class DummyPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => DummyPageState();
}

class DummyPageState extends State<DummyPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Dummy')),
      body: Center(
        child: Text('dummy'),
      ),
    );
  }
}

`

**Comment by jpnurmi** [comment] 2022-08-11 09:06
Thanks, I was able to reproduce the issue after adding an extra `setState()` call to force a rebuild. I've pushed a fix proposal: https://github.com/toshiaki-h/split_view/pull/20

**Closed** 2022-08-12 08:57 UTC

**Comment by ozzy1873** [comment] 2022-08-17 12:00
I can confirm that the bug is fixed in 3.2.1. Thanks!
